name: multipass
version: 'git'
version-script: |
  git describe
summary: Ubuntu at your fingertips
description: |
  Multipass gives you Ubuntu VMs in seconds. Just run `multipass launch`
  and it'll do all the setup for you. Check out `multipass find` for a list
  of available images. More details you can find under `multipass help`.

base: core18
grade: devel
confinement: classic

apps:
  multipassd:
    command: bin/launch-multipassd
    environment:
      LD_LIBRARY_PATH: $SNAP/lib:$SNAP/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/usr/lib:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET
      PATH: $SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$PATH
      QT_PLUGIN_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/qt5/plugins
      XDG_DATA_HOME: $SNAP_COMMON/data
      XDG_CACHE_HOME: $SNAP_COMMON/cache
    daemon: simple
    passthrough:
      after: [libvirt-bin]
  multipass:
    environment:
      LD_LIBRARY_PATH: $SNAP/lib:$SNAP/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/usr/lib:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET
      PATH: $SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$PATH
      QT_PLUGIN_PATH: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/qt5/plugins
    command: bin/multipass
    completer: etc/bash_completion.d/snap.multipass
  libvirt-bin:
    command: bin/launch-libvirtd
    environment:
      LD_LIBRARY_PATH: $SNAP/lib:$SNAP/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/usr/lib:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET
      PATH: $SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$PATH
      LC_ALL: C
    daemon: simple
  virtlogd-bin:
    command: bin/launch-virtlogd
    environment:
      LD_LIBRARY_PATH: $SNAP/lib:$SNAP/lib/$SNAPCRAFT_ARCH_TRIPLET:$SNAP/usr/lib:$SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET
      PATH: $SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$PATH
      LC_ALL: C
    daemon: simple
  virsh:
    command: bin/virsh
    environment:
      PATH: $SNAP/usr/sbin:$SNAP/usr/bin:$SNAP/sbin:$SNAP/bin:$PATH
      LC_ALL: C

parts:
  multipass:
    after:
    - libvirt
    plugin: cmake
    build-packages:
    - build-essential
    - cmake-extras
    - git
    - golang
    - libsystemd-dev
    - qtbase5-dev
    - qtbase5-dev-tools
    stage-packages:
    - libqt5core5a
    - libqt5network5
    - libxml2
    source: .
    configflags:
    - -DCMAKE_BUILD_TYPE=RelWithDebInfo
    - -DCMAKE_INSTALL_PREFIX=/
    - -DMULTIPASS_ENABLE_TESTS=off
    override-build: |
      snapcraftctl build
      set -e
      mkdir -p ${SNAPCRAFT_PART_INSTALL}/etc/bash_completion.d/
      echo 'export PATH="${PATH}:/snap/bin:/var/lib/snapd/snap/bin"' > ${SNAPCRAFT_PART_INSTALL}/etc/bash_completion.d/snap.multipass
      cat ../src/completions/bash/multipass >> ${SNAPCRAFT_PART_INSTALL}/etc/bash_completion.d/snap.multipass

  qemu:
    plugin: nil
    override-pull: ""
    stage-packages:
    - on amd64: [qemu-system-x86]
    - on i386: [qemu-system-x86]
    - on armhf: [qemu-system-arm]
    - on arm64: [qemu-system-arm]
    - qemu-utils
    - libslang2
    organize:
      usr/lib/*/pulseaudio/libpulsecommon-*.so: usr/lib/
      usr/share/seabios/bios-256k.bin: qemu/
      usr/share/seabios/vgabios-stdvga.bin: qemu/
      usr/share/seabios/kvmvapic.bin: qemu/
      usr/lib/ipxe/qemu/efi-virtio.rom: qemu/

  kvm-support:
    plugin: nil
    override-pull: ""
    stage-packages:
    - try: [msr-tools]

  libvirt:
    source: snap
    source-subdir: libvirt
    plugin: autotools
    build-packages:
    - libxml2-dev
    - libxml2-utils
    - libxml-libxml-perl
    - libcurl4-gnutls-dev
    - libncurses5-dev
    - libreadline-dev
    - zlib1g-dev
    - libgcrypt20-dev
    - libgnutls28-dev
    - libyajl-dev
    - libpcap0.8-dev
    - libaudit-dev
    - libdevmapper-dev
    - libpciaccess-dev
    - libnl-3-dev
    - libnl-route-3-dev
    - uuid-dev
    - try: [libnuma-dev]
    - python-all
    - python-six
    - wget
    - dpkg-dev
    - xsltproc
    stage-packages:
    - dmidecode
    - dnsmasq
    - dnsmasq-utils
    - ebtables
    - libxml2
    - try: [libnuma1]
    - libcurl3-gnutls
    - libpciaccess0
    - libpcap0.8
    configflags:
    - --with-qemu
    - --without-bhyve
    - --without-xen
    - --without-openvz
    - --without-vmware
    - --without-xenapi
    - --without-esx
    - --without-hyperv
    - --without-lxc
    - --without-vz
    - --without-vbox
    - --without-uml
    - --without-sasl
    - --without-storage-iscsi
    - --without-storage-sheepdog
    - --without-storage-rbd
    - --without-storage-lvm
    - --without-selinux
    - --prefix=/snap/$SNAPCRAFT_PROJECT_NAME/current
    - --localstatedir=/var/snap/$SNAPCRAFT_PROJECT_NAME/common
    - --sysconfdir=/var/snap/$SNAPCRAFT_PROJECT_NAME/common
    - DNSMASQ=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr/sbin/dnsmasq
    - DMIDECODE=/snap/$SNAPCRAFT_PROJECT_NAME/current/usr/sbin/dmidecode
    - EBTABLES_PATH=/snap/$SNAPCRAFT_PROJECT_NAME/current/sbin/ebtables
    - IPTABLES_PATH=/snap/$SNAPCRAFT_PROJECT_NAME/current/sbin/iptables
    - IP6TABLES_PATH=/snap/$SNAPCRAFT_PROJECT_NAME/current/sbin/ip6tables
    override-pull: |
      apt-get source libvirt
      mv libvirt-* libvirt
    organize:
      # Hack to shift installed libvirt back to root of snap
      # required to ensure that pathing to files etc works at
      # runtime
      # * is not used to avoid directory merge conflicts
      snap/multipass/current/: ./

  network-utils:
    plugin: nil
    override-pull: ""
    stage-packages:
    - iproute2
    - iptables
    - iputils-ping
    - libatm1
    - libxtables12

  glue:
    plugin: dump
    source: snap-wrappers
